### ISSUE TITLE
How to implement an await statement in a function?

### ISSUE THREAD

**Issue by MMoMM-org** [saml-dev/obsidian-custom-js#39] opened 2023-01-03 17:13 UTC
I would like to use dataview inside the customJS script.

`
        let dv = window.app.plugins.plugins.dataview.api;
        let pages = await dv.pages(from);
`
but if I use an await I get an error that this is only valid in an async function.

But if i declare my function with async function I get an error of "Unexpected Identifier" from customJS.

Might be something simple 😀

full code here: https://gist.github.com/MMoMM-org/3e609202788a6ed5c5781dab2e2466ee

**Comment by saml-dev** [comment] 2023-01-03 22:51
This is a limitation I can't work around. The weird "must be in a class" rule is caused by Obsidian limitations, and is required to get CustomJS working on mobile. Your only option is to use dv.pages in the `dataviewjs` block, then pass whatever you want into your CustomJS functions. For example
```
const {MyCode} = customJS
dv.pages('my/dir').where(MyCode.SomeFilterFunction)
```

**Comment by saml-dev** [comment] 2023-01-03 22:51
closing but feel free to reopen if you have other issues

**Closed by saml-dev** 2023-01-03 22:51 UTC

**Comment by Bjaux** [comment] 2023-03-08 19:27
I think I had the same issue when calling customJS from Templater, but when calling it from dataviewJS everything works just fine, something like
```
class CoolString {
  async coolify(field, value, file) { ...}
}
```
seems to be perfectly callable from within dataviewJS.
